port: PORT
testmode: TESTMODE
arweave:
  host: ARWEAVE_HOST
  port: ARWEAVE_PORT
  protocol: ARWEAVE_PROTOCOL
  key: ARWEAVE_KEY

log:
  level: LOG_LEVEL
  sendLogsTo: LOGSTASH_URL

queue:
  url: QUEUE_URL
  hostname: QUEUE_HOST
  username: QUEUE_USER
  password: QUEUE_PASSWORD
  port: QUEUE_PORT

