port: 80
testmode: 0
arweave:
  host: arweave.net
  port: 443
  protocol: https
  key: ''

storage:
  arweave_experiment_version_major: 1
  arweave_experiment_version_minor: 8
  arweave_gateway_url: https://arweave.net/graphql

log:
  level: info
  sendLogsTo: https://logstash.pointspace.io:12201

queue:
  url: amqp://localhost

chunk_id_verifier:
  max_concurrency: 50
  min_requeue_after_error_time: 5
  max_requeue_after_error_time: 15

arweave_tx_verifier:
  max_concurrency: 50
  min_verify_tx_interval: 20
  max_verify_tx_interval: 30
  discard_tx_timeout: 90
  min_txs_confirmations: 5
  min_requeue_after_error_time: 5
  max_requeue_after_error_time: 15