name: Deploy-To-Heroku-Staging
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          dontuseforce: 1
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: arweave-verifier-staging
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://arweave-verifier-staging.herokuapp.com/health"
          delay: 6
          usedocker: true

        env:
          HD_ARWEAVE_HOST: arweave.net
          HD_ARWEAVE_PORT: 443
          HD_ARWEAVE_KEY: ${{secrets.ARWEAVE_PROD_KEY}}
          HD_ARWEAVE_PROTOCOL: https
          HD_LOG_LEVEL: ${{secrets.LOG_LEVEL}}
          HD_LOGSTASH_URL: ${{secrets.LOGSTASH_URL}}
