name: Deploy-To-Heroku-Prod

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          dontuseforce: 1
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: arweave-verifier-prod
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://arweave-verifier-prod.herokuapp.com/health"
          delay: 5
          usedocker: true

        env:
          HD_ARWEAVE_HOST: arweave.net
          HD_ARWEAVE_PORT: 443
          HD_ARWEAVE_KEY: ${{secrets.ARWEAVE_PROD_KEY}}
          HD_ARWEAVE_PROTOCOL: https
          HD_LOG_LEVEL: ${{secrets.LOG_LEVEL}}
          HD_LOGSTASH_URL: ${{secrets.LOGSTASH_URL}}
          HD_QUEUE_URL: ${{secrets.QUEUE_URL}}
          HD_QUEUE_HOST: ${{secrets.QUEUE_HOST}}
          HD_QUEUE_USER: ${{secrets.QUEUE_USER}}
          HD_QUEUE_PASSWORD: ${{secrets.QUEUE_PASSWORD}}
